[package]
name = "verifier"
version = "0.1.0"
edition = "2021"

[dependencies]
circuit = { path = "../circuit" }
field = { path = "../field" }
prover = { path = "../prover" }
polynomial = { path = "../polynomial" }
rand = "0.8"
ark-ff = "0.4"
